# Generated by Django 4.0.4 on 2022-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
    ]
