# Generated by Django 4.0.4 on 2022-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_app', '0002_employee2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee2',
            name='password',
            field=models.CharField(default='1', max_length=40),
        ),
    ]
